server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: markdown-notes
  
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.147.90:3306/markdown_notes?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: M22/B6!DxoDw
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: MarkdownNotesHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  # File Upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.markdown.notes.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
jwt:
  secret: "aGVsbG93b3JsZDEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg=="
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
  header: Authorization
  prefix: "Bearer "

# Alibaba Cloud Configuration
alibaba:
  dashscope:
    api-key: sk-6873d82a6bcf4abd9619c6c1fdb5cf3a
    model: qwen-turbo

# File Storage Configuration
storage:
  type: local # local or oss
  local:
    path: /data/markdown-notes/uploads
    url-prefix: http://localhost:8080/api/files
  oss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 

# Logging Configuration
logging:
  level:
    root: INFO
    com.markdown.notes: DEBUG
  file:
    name: logs/markdown-notes.log
    max-size: 10MB
    max-history: 30

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true